min_version = { soft = "2026.5.15", hard = "2026.5.12" }

[tools]
deno = "2.8.0"
node = "26.2.0"
pnpm = "11.3.0"

gh = "2.92.0"

mdbook = "0.5.3"
"github:lzanini/mdbook-katex" = "0.10.0-alpha-binaries"

"github:git-town/git-town" = "23.0.1"

[tasks.check]
description = "Task group for CI checks"
run = [
    { task = "install:frozen" },
    { task = "build:deps" },
    { task = "build" },
    { tasks = [
        "lint",
        "*:check",
    ] },
    { task = "format" },
    { task = "test:e2e:install-deps" },
    { tasks = [
        "test:e2e",
    ] },
]

